<p>Search using library of congress subject headings. For example:</p>
<ul>
<li>english language dictionaries spanish</li>
<li>learning, psychology of</li>
<li>nervous system</li>
<li>theater england history</li>
<li>united states history civil war 1860 1865</li>
</ul>
<p>The subject search uses a specific, controlled vocabulary for describing library material. If you do not find what you are looking for in the subject index, try an <a href="/search/X">advanced search</a> or ask a Librarian for assistance.</p>