<p>Type in the ISBN, ISSN or LCCN exactly as cited. Punctuation and spaces can be omitted if desired. For example:</p>
<ul>    
<li>International Standard Serial Number (ISSN)
    <ul>
    <li>0040-781x</li>
    <li>0033 3107</li>
    </ul>
</li>
<li>International Standard Book Number (ISBN)
    <ul> 
    <li>0201112116</li>
    <li>0123467652</li>
    </ul>
</li>
<li>Record Label Numbers
    <ul>
    <li>SP-33-143</li>
    <li>RCA LM 1080</li>
    </ul>
</li>
<li>LCCN
    <ul>
    <li>79-51608</li>
    <li>agr-04394</li>
    <li>agr04003603</li>
</li>
</ul>